[platformio]
src_dir = src
include_dir = include

[cdp_common]
monitor_speed = 115200
monitor_filters = time
build_flags =
    -std=gnu++2a
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_NONE
    -D CDP_DEBUG
    -DRADIOLIB_EXCLUDE_CC1101
    -DRADIOLIB_EXCLUDE_NRF24
    -DRADIOLIB_EXCLUDE_RF69
    -DRADIOLIB_EXCLUDE_SX1231
    -DRADIOLIB_EXCLUDE_SX1233
    -DRADIOLIB_EXCLUDE_SX128X
    -DRADIOLIB_EXCLUDE_SI443X
    -DRADIOLIB_EXCLUDE_RFM2X
    -DRADIOLIB_EXCLUDE_AFSK
    -DRADIOLIB_EXCLUDE_BELL
    -DRADIOLIB_EXCLUDE_HELLSCHREIBER
    -DRADIOLIB_EXCLUDE_MORSE
    -DRADIOLIB_EXCLUDE_RTTY
    -DRADIOLIB_EXCLUDE_SSTV
    -DRADIOLIB_EXCLUDE_AX25
    -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE
    -DRADIOLIB_EXCLUDE_PAGER
    -DRADIOLIB_EXCLUDE_FSK4
    -DRADIOLIB_EXCLUDE_APRS
    -DRADIOLIB_EXCLUDE_LLCC68
build_unflags=
    -std=gnu++11

[esp32_base]
extends = cdp_common
platform = espressif32@6.12.0
board = esp32dev
build_flags = ${cdp_common.build_flags}
lib_deps =
    paulstoffregen/Time@^1.6.1
    contrem/arduino-timer @ ^2.3.0
    knolleary/PubSubClient@^2.8
    tobiasschuerg/ESP8266 Influxdb@^3.13.1
    https://github.com/rock7/RockBLOCK-9704.git
    https://github.com/Project-Owl/QuackPack-Base.git
    https://github.com/Project-Owl/QuackPack-DuckDisplay.git

[env:heltec_wifi_lora_32_V2]
extends = esp32_base
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = time
board_build.partitions = huge_app.csv
upload_port = COM11
lib_deps =
    ${esp32_base.lib_deps}
;t-beam sx1276
[env:ttgo-lora32-v1]
extends = esp32_base
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
monitor_filters = time
board_build.partitions = huge_app.csv
build_flags =
    ${cdp_common.build_flags}
    -DTTGO_1_3
lib_deps =
    ${esp32_base.lib_deps}

[env:ttgo-t-beam]
extends = esp32_base
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
monitor_filters = time
board_build.partitions = huge_app.csv
build_flags =
    ${esp32_base.build_flags}
    -D ARDUINO_T_BEAM_SX1262
lib_deps =
    ${esp32_base.lib_deps}

;paxcounter
[env:ttgo-lora32-v21]
extends = esp32_base
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
monitor_filters = time
board_build.partitions = huge_app.csv
upload_port = COM10
build_flags =
    ${esp32_base.build_flags}
lib_deps =
    ${esp32_base.lib_deps}

[env:heltec_wifi_lora_32_V3]
extends = esp32_base
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = time
upload_port = COM1
build_flags =
    ${esp32_base.build_flags}
lib_deps =
    ${esp32_base.lib_deps}